USE Bank;

DROP TRIGGER IF EXISTS TR_INIT_CUSTOMER;
DELIMITER //
CREATE TRIGGER TR_INIT_CUSTOMER
AFTER INSERT ON T_CUSTOMER
FOR EACH ROW
BEGIN
INSERT INTO T_ACCOUNT (ACCOUNT_ID, ACCOUNT_TYPE, AMOUNT) VALUES (NEW.ACCOUNT_ID, 1, 0);
INSERT INTO T_ACCOUNT (ACCOUNT_ID, ACCOUNT_TYPE, AMOUNT) VALUES (NEW.ACCOUNT_ID, 2, 0);
END//
DELIMITER ;

#DROP TRIGGER IF EXISTS WITHDRAW_TR;
#DELIMITER //
#CREATE TRIGGER WITHDRAW_TR
#AFTER INSERT ON T_ACCOUNT
#FOR EACH ROW
#BEGIN
#INSERT INTO T_TRANSANCTION_HISTORY SELECT NEW.ACCOUNT_ID, 7 ,NEW.ACCOUNT_TYPE, NEW.AMOUNT, CURRENT_TIMESTAMP;
#END//
#DELIMITER ;

#DROP TRIGGER IF EXISTS DEPOSIT_TR;
#DELIMITER //
#CREATE TRIGGER DEPOSIT_TR
#AFTER INSERT ON T_ACCOUNT
#FOR EACH ROW
#BEGIN
#INSERT INTO T_TRANSANCTION_HISTORY SELECT NEW.ACCOUNT_ID, 7 ,NEW.ACCOUNT_TYPE, NEW.AMOUNT, CURRENT_TIMESTAMP;
#END//
#DELIMITER ;


DROP PROCEDURE IF EXISTS SP_VIEW_BALANCE;
DELIMITER //
CREATE PROCEDURE SP_VIEW_BALANCE(IN
P_ACCOUNT_ID INT,
P_ACCOUNT_TYPE INT)
BEGIN
SELECT AMOUNT
FROM T_ACCOUNT
WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
END//Zz
DELIMITER ;

DROP PROCEDURE IF EXISTS SP_WITHDRAW_AMOUNT;
DELIMITER //
CREATE PROCEDURE SP_WITHDRAW_AMOUNT(IN
P_ACCOUNT_ID INT,
P_ACCOUNT_TYPE INT,
P_NEW_BALANCE DOUBLE)
BEGIN
	UPDATE T_ACCOUNT 
	SET AMOUNT = AMOUNT - P_NEW_BALANCE 
	WHERE ACCOUNT_ID = P_ACCOUNT_ID 
		AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE, ACCOUNT_TYPE, AMOUNT)
VALUES (P_ACCOUNT_ID, 3, P_ACCOUNT_TYPE, P_NEW_BALANCE);
SELECT AMOUNT FROM T_ACCOUNT WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
END//
DELIMITER ;


DROP PROCEDURE IF EXISTS SP_DEPOSIT_AMOUNT;
DELIMITER //
CREATE PROCEDURE SP_DEPOSIT_AMOUNT(IN
P_ACCOUNT_ID INT,
P_ACCOUNT_TYPE INT,
P_NEW_BALANCE DOUBLE)
BEGIN
UPDATE T_ACCOUNT
SET AMOUNT = AMOUNT + P_NEW_BALANCE
WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE, ACCOUNT_TYPE, AMOUNT)
VALUES (P_ACCOUNT_ID, 4, P_ACCOUNT_TYPE, P_NEW_BALANCE);
SELECT AMOUNT FROM T_ACCOUNT WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
END//
DELIMITER ;

DROP PROCEDURE IF EXISTS SP_DELETE_ACCOUNT;
DELIMITER //
CREATE PROCEDURE SP_DELETE_ACCOUNT(IN
P_USERNAME VARCHAR(50),
P_PASSWORD VARCHAR(50))
BEGIN
UPDATE T_CUSTOMER SET ACTIVE = 0 WHERE USERNAME = P_USERNAME AND PASS = P_PASSWORD;

INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE)
VALUES (P_ACCOUNT_ID, 6);

IF EXISTS(SELECT ACTIVE FROM T_CUSTOMER WHERE USERNAME = P_USERNAME AND PASS = P_PASSWORD AND ACTIVE = 0) THEN 
SELECT 1 AS result;
ELSE SELECT 0 AS result;
END IF;
END//
DELIMITER  ;

DROP PROCEDURE IF EXISTS SP_CREATE_ACCOUNT;
DELIMITER //
CREATE PROCEDURE SP_CREATE_ACCOUNT(IN
P_F_NAME VARCHAR(50),
P_L_NAME VARCHAR(50),
P_EMAIL VARCHAR(50), 
P_USERNAME VARCHAR(50),
P_PASS VARCHAR(50))
BEGIN
INSERT INTO T_CUSTOMER (EMAIL, F_NAME, L_NAME, USERNAME, PASS)
VALUES (P_EMAIL, P_F_NAME, P_L_NAME, P_USERNAME, P_PASS);

#This is the correalted query
INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE)
SELECT ACCOUNT_ID,7 FROM T_CUSTOMER WHERE USERNAME = P_USERNAME;


SELECT ACCOUNT_ID
FROM T_CUSTOMER
WHERE USERNAME = P_USERNAME ;
END//
DELIMITER ;



DROP PROCEDURE IF EXISTS SP_LOGIN;
DELIMITER //
CREATE PROCEDURE SP_LOGIN(IN
P_USERNAME VARCHAR(50),
P_PASSWORD VARCHAR(50))
BEGIN
	IF EXISTS(SELECT ACCOUNT_ID FROM T_CUSTOMER WHERE USERNAME = P_USERNAME AND PASS = P_PASSWORD AND ACTIVE = 0)
		THEN SELECT -1 AS ACCOUNT_ID;
	ELSEIF EXISTS(SELECT ACCOUNT_ID FROM T_CUSTOMER WHERE USERNAME = P_USERNAME AND PASS = P_PASSWORD AND ACTIVE = 1)
		THEN SELECT ACCOUNT_ID FROM T_CUSTOMER WHERE USERNAME = P_USERNAME AND PASS = P_PASSWORD AND ACTIVE = 1;
	ELSE SELECT -2 AS ACCOUNT_ID;
	END IF;
	UPDATE T_CUSTOMER
	SET LAST_LOGIN_DATE = CURRENT_TIMESTAMP WHERE USERNAME = P_USERNAME;
END//
DELIMITER  ;

DROP PROCEDURE IF EXISTS SP_CHECK_USERNAME;
DELIMITER //
CREATE PROCEDURE SP_CHECK_USERNAME(IN
P_USERNAME VARCHAR(50))
BEGIN
IF EXISTS(SELECT ACCOUNT_ID FROM T_CUSTOMER WHERE USERNAME = P_USERNAME) THEN SELECT 1 AS result;
ELSE SELECT 0 AS result;
END IF;
END//
DELIMITER  ;

DROP PROCEDURE IF EXISTS SP_TRANSFER_AMOUNT;
DELIMITER //
CREATE PROCEDURE SP_TRANSFER_AMOUNT(IN
P_ACCOUNT_ID INT,
P_ACCOUNT_TYPE INT,
P_TO_ACCOUNT_ID INT,
P_TO_ACCOUNT_TYPE INT,
P_NEW_BALANCE DOUBLE)
BEGIN
UPDATE T_ACCOUNT
SET AMOUNT = AMOUNT - P_NEW_BALANCE
WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;

UPDATE T_ACCOUNT
SET AMOUNT = AMOUNT + P_NEW_BALANCE
WHERE ACCOUNT_ID = P_TO_ACCOUNT_ID AND ACCOUNT_TYPE = P_TO_ACCOUNT_TYPE;

INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE, ACCOUNT_TYPE, AMOUNT)
VALUES (P_ACCOUNT_ID, 5, P_ACCOUNT_TYPE, 0-P_NEW_BALANCE);

INSERT INTO T_TRANSANCTION_HISTORY (ACCOUNT_ID, TRANSANCTION_TYPE, ACCOUNT_TYPE, AMOUNT)
VALUES (P_TO_ACCOUNT_ID, 5, P_TO_ACCOUNT_TYPE, P_NEW_BALANCE);

SELECT AMOUNT FROM T_ACCOUNT WHERE ACCOUNT_ID = P_ACCOUNT_ID AND ACCOUNT_TYPE = P_ACCOUNT_TYPE;
END//
DELIMITER ;

DROP PROCEDURE IF EXISTS SP_ACCOUNT_EXISTS;
DELIMITER //
CREATE PROCEDURE SP_ACCOUNT_EXISTS(IN
P_ACCOUNT_ID INT)
BEGIN
	SELECT ACCOUNT_ID FROM T_CUSTOMER WHERE ACCOUNT_ID = P_ACCOUNT_ID;
END//
DELIMITER ;

#TODO MISSING ONE MORE TRIGGER




