DROP DATABASE IF EXISTS Bank;
CREATE DATABASE Bank;
USE Bank; 

DROP TABLE IF EXISTS T_ACCOUNT;
CREATE TABLE T_ACCOUNT
(
	 ACCOUNT_ID INT AUTO_INCREMENT Not Null,
	 EMAIL VARCHAR(50),
	 F_NAME VARCHAR(30) NOT NULL,
	 L_NAME VARCHAR(50) NOT NULL,
	 USERNAME VARCHAR(50) Not Null,
	 PASS VARCHAR(50) Not Null,
	 ACTIVE BOOLEAN DEFAULT TRUE NOT NUll,
	 CREATED_ON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	 LAST_UPDATE_DATE DATETIME,
	 PRIMARY KEY(ACCOUNT_ID)
);

DROP TABLE IF EXISTS ACCOUNT_AMOUNT;
CREATE TABLE T_CASH_AMOUNT
(
	ACCOUNT_ID INT Not Null,
 	SAVINGS_AMOUNT BIGINT DEFAULT 0,
 	CHECKING_AMOUNT BIGINT DEFAULT 0,
 	SAVINGS_LAST_UPDATED timestamp,
 	CHECKING_LAST_UPDATED timestamp,
 	PRIMARY KEY (ACCOUNT_ID),
 	FOREIGN KEY (ACCOUNT_ID) references T_ACCOUNT (ACCOUNT_ID)
 	ON UPDATE CASCADE
) ;

DROP TABLE IF EXISTS T_CODES;
CREATE TABLE T_CODES
(
	CODE_ID INT AUTO_INCREMENT Not Null,
	CODE_TYPE VARCHAR(10) Not Null,
	CODE_DESC VARCHAR(1000) Not Null,
	CREATED_ON DATETIME DEFAULT current_timestamp Not Null,
	PRIMARY KEY (CODE_ID)
) ;

DROP TABLE IF EXISTS T_TRANSANCTION_HISTORY;
CREATE TABLE T_TRANSANCTION_HISTORY
(
	ACCOUNT_ID INT Not Null,
	TRANSANCTION_TYPE INT NOT NULL,
	ACCOUNT_TYPE INT NOT NULL,
	AMOUNT bigint NOT NULL,
	TRANSANCTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, TRANSANCTION_DATE),
    FOREIGN KEY (TRANSANCTION_TYPE) references T_CODES (CODE_ID)
	ON UPDATE CASCADE,
	FOREIGN KEY (ACCOUNT_TYPE) references T_CODES (CODE_ID)
	ON UPDATE CASCADE,
	FOREIGN KEY (ACCOUNT_ID) references T_ACCOUNT (ACCOUNT_ID)
 	ON UPDATE CASCADE
	
	
) 


