DROP DATABASE IF EXISTS Bank;
CREATE DATABASE Bank;
USE Bank; 

DROP TABLE IF EXISTS T_ACCOUNT;
CREATE TABLE T_ACCOUNT
(
	 ACCOUNT_ID INT AUTO_INCREMENT Not Null,
	 EMAIL VARCHAR(50),
	 F_NAME VARCHAR(30) NOT NULL,
	 L_NAME VARCHAR(50) NOT NULL,
	 USERNAME VARCHAR(50) Not Null,
	 PASS VARCHAR(50) Not Null,
	 ACTIVE BOOLEAN DEFAULT TRUE NOT NUll,
	 CREATED_ON DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	 LAST_LOGIN_DATE DATETIME,
	 PRIMARY KEY(ACCOUNT_ID, USERNAME)
);

DROP TABLE IF EXISTS T_CODES;
CREATE TABLE T_CODES
(
	CODE_ID INT AUTO_INCREMENT Not Null,
    CODE_KEY VARCHAR(5) Not null,
	CODE_TYPE VARCHAR(10) Not Null,
	CODE_DESC VARCHAR(1000) Not Null,
	CREATED_ON DATETIME DEFAULT current_timestamp Not Null,
	PRIMARY KEY (CODE_ID)
) ;

DROP TABLE IF EXISTS T_CASH_AMOUNT;
CREATE TABLE T_CASH_AMOUNT
(
	ACCOUNT_ID INT Not Null,
    ACCOUNT_TYPE INT not Null,
 	AMOUNT BIGINT DEFAULT 0,
 	LAST_UPDATED timestamp DEFAULT current_timestamp,
 	PRIMARY KEY (ACCOUNT_ID, ACCOUNT_TYPE),
 	FOREIGN KEY (ACCOUNT_ID) references T_ACCOUNT (ACCOUNT_ID)
 	ON UPDATE CASCADE,
    FOREIGN KEY (ACCOUNT_TYPE) references T_CODES (CODE_ID)
 	ON UPDATE CASCADE
) ;


DROP TABLE IF EXISTS T_TRANSANCTION_HISTORY;
CREATE TABLE T_TRANSANCTION_HISTORY
(
	ACCOUNT_ID INT Not Null,
	TRANSANCTION_TYPE INT NOT NULL,
	ACCOUNT_TYPE INT NOT NULL,
	AMOUNT bigint NOT NULL,
	TRANSANCTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, TRANSANCTION_DATE,TRANSANCTION_TYPE,ACCOUNT_TYPE),
    FOREIGN KEY (TRANSANCTION_TYPE) references T_CODES (CODE_ID)
	ON UPDATE CASCADE,
	FOREIGN KEY (ACCOUNT_TYPE) references T_CODES (CODE_ID)
	ON UPDATE CASCADE,
	FOREIGN KEY (ACCOUNT_ID) references T_ACCOUNT (ACCOUNT_ID)
 	ON UPDATE CASCADE
	
	
) ;

LOAD DATA LOCAL INFILE '/home/viviturtle/School/CS157a/School/Codes.txt' 
INTO TABLE T_CODES 
FIELDS TERMINATED BY ','
(CODE_KEY, CODE_TYPE, CODE_DESC)
SET CODE_ID = NULL AND CREATED_ON = NULL;